/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type Resource = {
  _type: "resource";
  type: "link" | "article" | "pdf" | "video" | "download";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon: string;
  title: string;
  description: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration: string;
  freePreview?: boolean;
  studentCount?: number;
  notes?: BlockContent;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level: "beginner" | "intermediate" | "advanced";
  price: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor: InstructorReference;
  category: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: Array<string>;
  bio: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    coverImage,    level,    price,    popular,    studentCount,    instructor->{name, "slug": slug.current, photo},    category->{title, "slug": slug.current},  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level: "advanced" | "beginner" | "intermediate";
  price: number;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    name: string;
    slug: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  category: {
    title: string;
    slug: string;
  };
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{"slug": slug.current}
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    coverImage,    level,    price,    popular,    studentCount,    learningOutcomes[]{_key, icon, title, description},    instructor->{_id, name, "slug": slug.current, photo, expertise, bio},    category->{_id, title, "slug": slug.current},    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        title,        "slug": slug.current,        duration,        freePreview,        studentCount,        poster,      },    },  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level: "advanced" | "beginner" | "intermediate";
  price: number;
  popular: boolean | null;
  studentCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string;
    title: string;
    description: string;
  }> | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    expertise: Array<string> | null;
    bio: string;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      duration: string;
      freePreview: boolean | null;
      studentCount: number | null;
      poster: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    videoUrl,    poster,    duration,    freePreview,    studentCount,    notes,    keyPoints,    proTip,    resources[]{_key, type, title, description, url},  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  duration: string;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: BlockContent | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "download" | "link" | "pdf" | "video";
    title: string;
    description: string | null;
    url: string;
  }> | null;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)]{"slug": slug.current}
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: COURSE_FOR_LESSON_QUERY
// Query: *[_type == "course" && references($lessonId)][0]{    _id,    title,    "slug": slug.current,    modules[]{      _key,      title,      lessons[]->{_id, "slug": slug.current},    },  }
export type COURSE_FOR_LESSON_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  modules: Array<{
    _key: string;
    title: string;
    lessons: Array<{
      _id: string;
      slug: string;
    }> | null;
  }> | null;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    photo,    expertise,    bio,  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise: Array<string> | null;
  bio: string;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)]{"slug": slug.current}
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: COURSES_BY_INSTRUCTOR_QUERY
// Query: *[_type == "course" && instructor._ref == $instructorId] | order(title asc) {    _id,    title,    "slug": slug.current,    coverImage,    level,    studentCount,  }
export type COURSES_BY_INSTRUCTOR_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level: "advanced" | "beginner" | "intermediate";
  studentCount: number | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    instructor->{name, "slug": slug.current, photo},\n    category->{title, "slug": slug.current},\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]{"slug": slug.current}\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    learningOutcomes[]{_key, icon, title, description},\n    instructor->{_id, name, "slug": slug.current, photo, expertise, bio},\n    category->{_id, title, "slug": slug.current},\n    modules[]{\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        duration,\n        freePreview,\n        studentCount,\n        poster,\n      },\n    },\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    poster,\n    duration,\n    freePreview,\n    studentCount,\n    notes,\n    keyPoints,\n    proTip,\n    resources[]{_key, type, title, description, url},\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)]{"slug": slug.current}\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && references($lessonId)][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    modules[]{\n      _key,\n      title,\n      lessons[]->{_id, "slug": slug.current},\n    },\n  }\n': COURSE_FOR_LESSON_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    photo,\n    expertise,\n    bio,\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)]{"slug": slug.current}\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && instructor._ref == $instructorId] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage,\n    level,\n    studentCount,\n  }\n': COURSES_BY_INSTRUCTOR_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n  }\n': CATEGORIES_QUERY_RESULT;
  }
}
